### ISSUE TITLE
Incorrect normalisation of units

### ISSUE THREAD

**Issue by madgen** [camfort/camfort#28] opened 2016-07-21 15:28 UTC
```fortran
program normal_form
  != unit u1 / (u2 / u3) :: x
  integer x

  != unit u1 / (u2 * u3) :: y
  integer y = 10

  x = y
end program normal_form
```

This is interpreted as consistent under `units-check` on new-units branch (CC @mrd). But it throws an error on master.

I think both behaviours are wrong.

**Comment by dorchard** [comment] 2016-08-22 19:59
This bug remains.

**Comment by mrd** [comment] 2016-08-24 14:49
This is not to do with normalisation but rather to do with parsing.

The new units parser does not lex or parse the '*' operator.

**Comment by mrd** [comment] 2016-09-06 10:20
Duplicate of #30.

**Closed by mrd** 2016-09-06 10:20 UTC
Labels: units-of-measure
